<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 16.10.2017
 * Time: 20:47
 */
function getNodesCountByTaxonomyTermIds($termIds){
  $termIds = (array) $termIds;
  if(empty($termIds)){
    return NULL;
  }

  $query = \Drupal::database()->select('taxonomy_index', 'ti');
  $query->addExpression('COUNT(DISTINCT ti.nid)');
  $query->condition('ti.tid', $termIds, 'IN');
  $query->distinct(TRUE);
  $result = $query->execute();

  if($nodesCount = $result->fetchField()){
    return $nodesCount;
  }

  return 0;
}

function getNodesByTaxonomyTermIds($termIds){
  $termIds = (array) $termIds;
  if(empty($termIds)){
    return NULL;
  }

  $query = \Drupal::database()->select('taxonomy_index', 'ti');
  $query->innerJoin('node_field_data' , 'nfd' , 'nfd.nid = ti.nid');
  $query->condition('ti.tid', $termIds, 'IN');
  $query->fields('nfd', array('type'));
  $query->addExpression('COUNT(DISTINCT ti.nid)');
  $query->groupBy('nfd.type');
  $result = $query->execute();

  if($nodesCount = $result->fetchAllKeyed()){
    return $nodesCount;
  }

  return 0;
}

/**
 * Implements hook_page_attachments().
 */
function alter_entity_autocomplete_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'alter_entity_autocomplete/alter-entity-autocomplete';
}

function alter_entity_autocomplete_localSort($a,$b){
  $arr = array('route'=> 1,'visit' => 2,'experience' => 3);
  return $arr[$a] - $arr[$b];
}