module:
  address: 0
  audiofield: 0
  automated_cron: 0
  backup_migrate: 0
  basic_auth: 0
  better_exposed_filters: 0
  blazy: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_provider: 0
  config_sync: 0
  config_translation: 0
  config_update: 0
  config_update_ui: 0
  consumers: 0
  contact: 0
  contact_block: 0
  content_translation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  features: 0
  features_ui: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  geolocation: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  image_url_formatter: 0
  interval: 0
  kint: 0
  language: 0
  link: 0
  link_css: 0
  locale: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  rest: 0
  rest_api_doc: 0
  rest_export_nested: 0
  restui: 0
  search: 0
  serialization: 0
  shortcut: 0
  simple_oauth: 0
  simple_oauth_extras: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  system: 0
  taxonomy: 0
  taxonomy_menu: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  video: 0
  views_field_view: 0
  views_ui: 0
  votingapi: 0
  votingapi_widgets: 0
  webprofiler: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  foundation: 0
  nl: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
