definitions:
  contact__site_page:
    weight: -50
    parent: 'menu_link_content:3daea573-69e7-4ebf-8df9-c4a2fa4f88aa'
    enabled: true
    menu_name: footer
    expanded: false
  standard__front_page:
    weight: -46
    menu_name: main
    parent: ''
    enabled: false
    expanded: false
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
