features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://logo_nl.png'
favicon:
  use_default: 1
google_maps_api_key: ''
to_top: 0
search_background_path: ''
search_background_upload: ''
social_facebook: ''
social_twitter: ''
social_pinterest: ''
social_google: ''
social_youtube: ''
