routes:
  - rest.entity.vote.GET.json
  - rest.entity.vote.POST
  - rest.entity.vote.DELETE
  - rest.entity.vote.PATCH
  - rest.entity.vote_result.GET.json
  - rest.entity.vote_result.POST
  - rest.entity.vote_result.DELETE
  - rest.entity.vote_result.PATCH
overview: '<h2>Overview</h2>This describes the resources that make up the REST API for [site:name].'
_core:
  default_config_hash: eLI6JHGFThSgw97yVhmmm15FSFUbfirxL6qoHoWMFZw
