label: Llengua
tips:
  language-overview:
    label: Lleng端es
  language-add:
    label: 'Afegint lleng端es'
  language-reorder:
    label: 'Reordenament de les lleng端es'
  language-default:
    label: 'Estableix l''idioma per defecte'
  language-operations:
    label: 'Modificant les lleng端es'
